# Generated by Django 2.2.1 on 2019-06-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Patient's Name")),
                ('dob', models.CharField(blank=True, max_length=200, null=True, verbose_name='DOB')),
                ('sex', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sex')),
                ('date_of_surgery', models.CharField(blank=True, max_length=200, null=True, verbose_name='Date of Surgery')),
                ('claim_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Claim No')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('injury', models.TextField(blank=True, null=True, verbose_name='Injury')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('social_history', models.TextField(blank=True, null=True, verbose_name='Social History')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical History')),
                ('impression', models.TextField(blank=True, null=True, verbose_name='Impression')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_name', to='evaluators.Document')),
            ],
        ),
    ]
