# Generated by Django 2.2.1 on 2019-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0002_auto_20190613_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentdetail',
            options={'verbose_name': 'Document Detail', 'verbose_name_plural': 'Document Details'},
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Doctor's Name"),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='medicines',
            field=models.TextField(blank=True, null=True, verbose_name='medicines'),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='vital_signs',
            field=models.TextField(blank=True, null=True, verbose_name='vital_signs'),
        ),
    ]
