# Generated by Django 2.2.1 on 2019-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0003_auto_20190709_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='general',
            field=models.TextField(blank=True, null=True, verbose_name='general'),
        ),
    ]
